class CreateInstitucions < ActiveRecord::Migration[5.1]
  def change
    create_table :institucions do |t|
      t.string :nombre
      t.string :personaencargada
      t.string :cargo
      t.string :direccion
      t.string :departamento
      t.string :municipio
      t.string :localidad
      t.string :telefono
      t.string :fax
      t.string :paginweb
      t.string :nombrecontacto
      t.string :cargi
      t.string :tiempoencargo
      t.string :direccion
      t.string :telefono
      t.string :celular
      t.string :email
      t.string :institucionpublica
      t.text :detalle
      t.boolean :institucionprivada
      t.text :detalleprivado
      t.string :sinfinesdelucro
      t.text :detallesinfinesdelucro
      t.boolean :grupovoluntario
      t.text :detalle
      t.boolean :coe
      t.boolean :coenacional
      t.boolean :coedepartalemtal
      t.boolean :coemunicipal
      t.boolean :mesassectoriales
      t.boolean :salud
      t.boolean :educacion
      t.boolean :aguaysaneamiento
      t.boolean :seguridadalimentaria
      t.boolean :gobernabilidadproteccion
      t.boolean :albergues
      t.boolean :recuperacion
      t.boolean :comisionesdepartales
      t.text :detallecomisiones
      t.boolean :comisionesmunicipalesCOEM
      t.text :detallesCOEM
      t.boolean :dgr
      t.boolean :ugr
      t.boolean :unete
      t.boolean :grus
      t.boolean :consorciodeong
      t.boolean :observatorios
      t.text :detallesobservatorio
      t.boolean :local
      t.text :detalleslocal
      t.boolean :otros
      t.text :otrosdetalle
      t.boolean :mandatogestionriesgo
      t.boolean :mandatoseguridad
      t.boolean :mandatootro
      t.text :mandatodetalle
      t.text :especialidadesmandato
      t.boolean :serviciotransporte
      t.boolean :serviciobusquedaperros
      t.boolean :serviciotelecomunicaciones
      t.boolean :serviciosincendiosurbanos
      t.boolean :servicioevaluacion
      t.boolean :servicioincendioforestal
      t.boolean :serviciosaludysaneamiento
      t.boolean :serviciomanejomateriales
      t.boolean :serviciobusquedayrescate
      t.boolean :serviciospublicos
      t.boolean :serviciobusquedayrescateenaltura
      t.boolean :servicioseguridad
      t.boolean :serviciosalvamiento
      t.boolean :salvamientoacuatico
      t.boolean :manejogeneral
      t.text :serviciodetalle
      t.boolean :respuestanaturales
      t.boolean :respuestahidrometeorologicas
      t.boolean :respuestainundaciones
      t.boolean :respuestariadas
      t.boolean :respuestavientosfuertes
      t.boolean :respuestageologicas
      t.boolean :respuestadeslizamiento
      t.boolean :respuestaderrumber
      t.boolean :respuestasismos
      t.boolean :respuestaotros
      t.text :respuestadetalle
      t.boolean :socionatural
      t.boolean :socioambiental
      t.boolean :socioincendio
      t.boolean :sociootro
      t.text :sociodetalle
      t.boolean :antropicas
      t.boolean :antropicasincendios
      t.boolean :antropicasotros
      t.text :antropicas
      t.boolean :otrossocios
      t.text :otrosdetallessocios
      t.text :eventosfrecuentes
      t.boolean :plandecontingencia
      t.boolean :planencasosi
      t.text :tareasprotocolo
      t.boolean :porcentajerespuesta
      t.boolean :plandeemergencia
      t.boolean :encasosiemergencia
      t.text :tareasemergencia
      t.boolean :protocolodeaccion
      t.boolean :encasosiprotocolo
      t.boolean :areaflujo
      t.boolean :arealogistica
      t.boolean :areacomunicaciones
      t.boolean :areatransporte
      t.boolean :areaevaluaciondemergencia
      t.boolean :areadocumentacion
      t.boolean :areaemergenciamedica
      t.boolean :areamovilizacion
      t.string :areaoperaciones
      t.boolean :areaseguridad
      t.boolean :areaotros
      t.text :areadetalle
      t.boolean :activacionesautomaticas
      t.boolean :medioradio
      t.boolean :mediotv
      t.boolean :mediofrecuencia
      t.boolean :mediollamadas
      t.boolean :otros
      t.text :mediosdetalles
      t.boolean :requerimientosuperios
      t.text :requerimientosuperiosdetalle
      t.text :requerimientootrodetalle
      t.text :observaciones
      t.boolean :situacionesactual
      t.boolean :trabajosiniciales
      t.boolean :caracteristicasestructurales
      t.boolean :consideracionespeciales
      t.boolean :estadotiempo
      t.boolean :mapasderiesgo
      t.boolean :seguridadyproteccion
      t.boolean :planosdellugar
      t.boolean :evacuaionemergencia
      t.boolean :estadisticas
      t.boolean :temasdesalud
      t.boolean :accionotro
      t.text :acciondetalle
      t.boolean :capacitadosincidentes
      t.text :capacitadosobservaciones
      t.text :coberturageogracia
      t.text :brazosoperativosareas
      t.boolean :recursoadministrativo
      t.integer :recursoadministrativo
      t.boolean :recursosoperativo
      t.integer :recursosoperativopersonas
      t.boolean :operativoactivo
      t.integer :operativoactivopersonas
      t.boolean :pasivosenreserva
      t.integer :pasivosenreservapersonas
      t.boolean :primap
      t.integer :primapersonas
      t.boolean :crecl
      t.integer :creclpersonas
      t.boolean :brec
      t.integer :brecpersonas
      t.boolean :especidalidadrescateactuatico
      t.integer :especialidadrescatepersonas
      t.boolean :manejadorperros
      t.integer :manejadorperrospersona
      t.boolean :cbsci
      t.integer :cbscipersonas
      t.boolean :extincionincendiosurbanos
      t.integer :extincionserviciosurbanospersonas
      t.boolean :incendiosforestales
      t.integer :incendiosforestalespersonas
      t.boolean :medicos
      t.integer :numeromedicos
      t.boolean :sbv
      t.integer :sbv
      t.boolean :appa
      t.integer :appapersonas
      t.boolean :cpi
      t.integer :cpipersonas
      t.boolean :especilidadcomunicaciones
      t.integer :especidalidadcomunicacionespersonas
      t.boolean :especialidadlogistica
      t.integer :especialidadlogicasticapersonas
      t.integer :ambulanciascantidad
      t.boolean :ambulanciasestado
      t.integer :ambulanciascapacidadpersonas
      t.text :ambulanciasobservaciones
      t.integer :transliviano
      t.boolean :translivianoestado
      t.integer :translivianopersonas
      t.text :translivianobservaciones
      t.integer :transpesado
      t.boolean :transpesadoestado
      t.integer :transpesadopersonas
      t.text :transpesadosobservaciones
      t.integer :patrullas
      t.boolean :patrullasestado
      t.integer :patrullaspersonas
      t.text :patrullasobservaciones
      t.integer :carrosbomberos
      t.boolean :carrosbomberosestado
      t.integer :carrosbomberospersonas
      t.text :carrosbomberosobservaciones
      t.integer :cisternas
      t.boolean :cisternasestado
      t.integer :cisternaspersonas
      t.text :cisternasobservaciones
      t.integer :maquinariapesada
      t.boolean :maquinariapesadaestado
      t.integer :maquinariapesadapersonas
      t.string :maquinariapesadaobservaciones
      t.integer :equiporadios
      t.boolean :equiporadios
      t.text :equiporadioobservaciones
      t.integer :comunicacionesatelital
      t.boolean :comunicacionsatelital
      t.text :satelitalobservaciones
      t.integer :gps
      t.boolean :gpsestado
      t.text :gpsobservaciones

      t.timestamps
    end
  end
end
